2023-04-18 11:09:05,017 INFO    MainThread:1329373 [wandb_setup.py:_flush():76] Configure stats pid to 1329373
2023-04-18 11:09:05,017 INFO    MainThread:1329373 [wandb_setup.py:_flush():76] Loading settings from /home/GRAMES.POLYMTL.CA/lobouz/.config/wandb/settings
2023-04-18 11:09:05,017 INFO    MainThread:1329373 [wandb_setup.py:_flush():76] Loading settings from /home/GRAMES.POLYMTL.CA/lobouz/github/contrast-agnostic-softseg-spinalcord/wandb/settings
2023-04-18 11:09:05,017 INFO    MainThread:1329373 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-04-18 11:09:05,017 INFO    MainThread:1329373 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-04-18 11:09:05,017 INFO    MainThread:1329373 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'monai_main.py', 'program': 'monai_main.py'}
2023-04-18 11:09:05,017 INFO    MainThread:1329373 [wandb_init.py:_log_setup():506] Logging user logs to /home/GRAMES.POLYMTL.CA/lobouz/github/contrast-agnostic-softseg-spinalcord/wandb/run-20230418_110905-w9bb1lw1/logs/debug.log
2023-04-18 11:09:05,017 INFO    MainThread:1329373 [wandb_init.py:_log_setup():507] Logging internal logs to /home/GRAMES.POLYMTL.CA/lobouz/github/contrast-agnostic-softseg-spinalcord/wandb/run-20230418_110905-w9bb1lw1/logs/debug-internal.log
2023-04-18 11:09:05,017 INFO    MainThread:1329373 [wandb_init.py:init():546] calling init triggers
2023-04-18 11:09:05,017 INFO    MainThread:1329373 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'only_eval': False, 'model': 'unetr', 'dataset': 'spine-generic_no-crop', 'dataset_json_name': 'dataset_binary', 'init_filters': 16, 'feature_size': 16, 'hidden_size': 768, 'mlp_dim': 3072, 'num_heads': 12, 'out_channel': 2, 'loss_func': 'dice', 'num_gpus': 1, 'num_workers': 4, 'precision': 32, 'max_epochs': 2500, 'batch_size': 2, 'optimizer': 'adamw', 'learning_rate': 0.0001, 'patience': 200, 'T_0': 100, 'enable_progress_bar': False, 'check_val_every_n_epochs': 30, 'model_name': 'unetr', 'save_path': '/home/GRAMES.POLYMTL.CA/lobouz/contrast_agnostic/models_unetr', 'continue_from_checkpoint': False, 'seed': 42, 'visualize_test_preds': False}
2023-04-18 11:09:05,017 INFO    MainThread:1329373 [wandb_init.py:init():602] starting backend
2023-04-18 11:09:05,017 INFO    MainThread:1329373 [wandb_init.py:init():606] setting up manager
2023-04-18 11:09:05,021 INFO    MainThread:1329373 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-04-18 11:09:05,024 INFO    MainThread:1329373 [wandb_init.py:init():613] backend started and connected
2023-04-18 11:09:05,030 INFO    MainThread:1329373 [wandb_init.py:init():701] updated telemetry
2023-04-18 11:09:05,087 INFO    MainThread:1329373 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-04-18 11:09:05,458 INFO    MainThread:1329373 [wandb_run.py:_on_init():2133] communicating current version
2023-04-18 11:09:05,517 INFO    MainThread:1329373 [wandb_run.py:_on_init():2142] got version response upgrade_message: "wandb version 0.14.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-04-18 11:09:05,517 INFO    MainThread:1329373 [wandb_init.py:init():789] starting run threads in backend
2023-04-18 11:09:08,318 INFO    MainThread:1329373 [wandb_run.py:_console_start():2114] atexit reg
2023-04-18 11:09:08,319 INFO    MainThread:1329373 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-04-18 11:09:08,319 INFO    MainThread:1329373 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-04-18 11:09:08,319 INFO    MainThread:1329373 [wandb_run.py:_redirect():2059] Redirects installed.
2023-04-18 11:09:08,320 INFO    MainThread:1329373 [wandb_init.py:init():831] run started, returning control to user process
2023-04-18 11:13:03,460 INFO    MainThread:1329373 [wandb_run.py:_config_callback():1251] config_cb None None {'args/only_eval': False, 'args/model': 'unetr', 'args/dataset': 'spine-generic_no-crop', 'args/dataset_json_name': 'dataset_binary', 'args/init_filters': 16, 'args/feature_size': 16, 'args/hidden_size': 768, 'args/mlp_dim': 3072, 'args/num_heads': 12, 'args/out_channel': 2, 'args/loss_func': 'dice', 'args/num_gpus': 1, 'args/num_workers': 4, 'args/precision': 32, 'args/max_epochs': 2500, 'args/batch_size': 2, 'args/optimizer': 'adamw', 'args/learning_rate': 0.0001, 'args/patience': 200, 'args/T_0': 100, 'args/enable_progress_bar': False, 'args/check_val_every_n_epochs': 30, 'args/model_name': 'unetr', 'args/save_path': '/home/GRAMES.POLYMTL.CA/lobouz/contrast_agnostic/models_unetr', 'args/continue_from_checkpoint': False, 'args/seed': 42, 'args/visualize_test_preds': False, 'data_root': '/home/GRAMES.POLYMTL.CA/lobouz/duke/projects/ivadomed/contrast-agnostic-seg/data_processed_sg_2023-03-10_NO_CROP/data_processed_clean/', 'net': None, 'loss_function': None, 'optimizer_class': 'AdamW'}
2023-04-18 11:15:02,042 INFO    MainThread:1329373 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 243, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/GRAMES.POLYMTL.CA/lobouz/miniconda3/envs/monai-unetr/lib/python3.8/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=10)
2023-04-18 11:16:20,073 WARNING MsgRouterThr:1329373 [router.py:message_loop():77] message_loop has been closed
